export const ICECHUNK_CATALOG = [
  {
    key: 'noaa-hrrr-forecast-48-hour-virtual',
    label: 'NOAA HRRR (High-Resolution Rapid Refresh)',
    subtitle: '3 km resolution, Continental US, hourly steps out to 48 hours',
    store: 'https://dynamical-noaa-hrrr.s3.us-west-2.amazonaws.com/noaa-hrrr-forecast-48-hour-virtual/v0.5.0.icechunk/',
  },
  {
    key: 'chirps-daily',
    label: 'CHIRPS Daily Precipitation',
    subtitle: '',
    store: 'https://data.source.coop/e4drr-project/observations/chirps_daily_icechunk',
  },
  {
    key: 'earthmover-era5-surface',
    label: 'Earthmover ERA5 Surface Reanalysis',
    subtitle: 'Multi-Variable',
    store: 'https://earthmover-icechunk-era5.s3.us-east-1.amazonaws.com/era5_surface_aws',
  },
  {
    key: 'noaa-gfs-forecast',
    label: 'NOAA GFS',
    subtitle: 'Global Weather Forecast',
    store: 'https://dynamical-noaa-gfs.s3.us-west-2.amazonaws.com/noaa-gfs-forecast/v0.2.7.icechunk/',
  },
  {
    key: 'dwd-icon-eu-forecast',
    label: 'DWD ICON-EU',
    subtitle: 'Numerical Weather Forecast',
    store: 'https://dynamical-dwd-icon-eu.s3.us-west-2.amazonaws.com/dwd-icon-eu-forecast-5-day/v0.2.0.icechunk/',
  },
  {
    key: 'ecmwf-aifs-single-forecast',
    label: 'ECMWF AIFS Single Forecast',
    subtitle: 'Artificial Intelligence Forecasting System',
    store: 'https://dynamical-ecmwf-aifs-single.s3.us-west-2.amazonaws.com/ecmwf-aifs-single-forecast/v0.1.0.icechunk/',
  },
  {
    key: 'metoffice-global-wave',
    label: 'UK Met Office Global Wave Forecast',
    subtitle: '',
    store: 'https://data.source.coop/bkr/metoffice/metoffice_global_wave.icechunk',
  },
  {
    key: 'metoffice-global-deterministic-6h',
    label: 'UK Met Office Global Deterministic Atmosphere Forecast',
    subtitle: '6-hourly 24hr',
    store: 'https://data.source.coop/bkr/metoffice/metoffice_global_deterministic_10km_6hourly_24hr.icechunk',
  },
  {
    key: 'nasa-geos-15min',
    label: 'NASA GEOS Atmospheric Reanalysis',
    subtitle: '15-minute',
    store: 'https://data.source.coop/bkr/geos/geos_15min.icechunk',
  },
  {
    key: 'metoffice-global-deterministic-11h',
    label: 'UK Met Office Global Deterministic Atmosphere Forecast',
    subtitle: '11-hour',
    store: 'https://data.source.coop/bkr/metoffice/metoffice_global_deterministic_10km_11hour.icechunk',
  },
  {
    key: 'metoffice-global-deterministic',
    label: 'UK Met Office Global Deterministic Atmosphere Forecast',
    subtitle: '',
    store: 'https://data.source.coop/bkr/metoffice/metoffice_global_deterministic_10km.icechunk',
  },
  {
    key: 'noaa-hrrr-analysis',
    label: 'NOAA HRRR',
    subtitle: 'High-Resolution Rapid Refresh Analysis',
    store: 'https://dynamical-noaa-hrrr.s3.us-west-2.amazonaws.com/noaa-hrrr-analysis/v0.2.0.icechunk/',
  },
  {
    key: 'noaa-mrms-conus-hourly',
    label: 'NOAA MRMS CONUS',
    subtitle: 'Hourly Radar-Based Precipitation Analysis',
    store: 'https://dynamical-noaa-mrms.s3.amazonaws.com/noaa-mrms-conus-analysis-hourly/v0.3.0.icechunk/',
  },
  {
    key: 'ecmwf-aifs-ens-forecast',
    label: 'ECMWF AIFS Ensemble Forecast',
    subtitle: '',
    store: 'https://dynamical-ecmwf-aifs-ens.s3.us-west-2.amazonaws.com/ecmwf-aifs-ens-forecast/v0.1.0.icechunk/',
  },
  {
    key: 'ecmwf-ifs-ens-15day',
    label: 'ECMWF IFS Ensemble 15-day Weather Forecast',
    subtitle: '0.25°',
    store: 'https://dynamical-ecmwf-ifs-ens.s3.us-west-2.amazonaws.com/ecmwf-ifs-ens-forecast-15-day-0-25-degree/v0.1.0.icechunk/',
  },
  {
    key: 'noaa-gefs-35day-forecast',
    label: 'NOAA GEFS 35-day Ensemble Forecast',
    subtitle: '',
    store: 'https://dynamical-noaa-gefs.s3.us-west-2.amazonaws.com/noaa-gefs-forecast-35-day/v0.2.0.icechunk/',
  },
  {
    key: 'silam-aerosol',
    label: 'SILAM Global Dust Model Forecasts',
    subtitle: 'Aerosol',
    store: 'https://data.source.coop/bkr/silam-dust/silam_aerosol.icechunk',
  },
  {
    key: 'cams-aerosol-analysis',
    label: 'CAMS Aerosol Analysis',
    subtitle: 'Copernicus CAMS Operational Archive',
    store: 'https://data.source.coop/bkr/cams/cams.icechunk',
  },
  {
    key: 'cams-aerosol-forecast',
    label: 'CAMS Aerosol Forecast',
    subtitle: 'Copernicus CAMS Operational Archive',
    store: 'https://data.source.coop/bkr/cams/cams_analysis_and_forecast.icechunk',
  },
  {
    key: 'nasa-rasi',
    label: 'NASA RASI',
    subtitle: 'Risk Analysis and Solutions Innovators',
    store: 'https://nasa-waterinsight.s3.us-west-2.amazonaws.com/virtual-zarr-store/icechunk/RASI/HISTORICAL/',
  },
  {
    key: 'alaska-hrrr',
    label: 'Alaska HRRR',
    subtitle: '',
    store: 'https://data.source.coop/bkr/dmi/alaska_hrrr.icechunk',
  },
  {
    key: 'ndvi-test',
    label: 'NDVI',
    subtitle: 'Normalized Difference Vegetation Index',
    store: 'https://data.source.coop/eeholmes/chlaz/icechunk',
  },
];